config/routes.rb
Rails.application.routes.draw do

  resources :questions

  resources :advertisements

  resources :topics do
  	resources :posts, except: [:index]
    resources :sponsored_posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  post 'users/confirm' => 'users#confirm'

  get 'about' => 'welcome#about'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
  	@questions = Question.all
  end

  def show
  	@question = Question.find(params[:id])
  end

  def new
  	@question = Question.new
  end

  def create
  	@question = Question.new(params.require(:question).permit(:title, :body, :resolved))
  	if @question.save
  		flash[:notice] = "Question was saved."
  		redirect_to @question
  	else
  		flash[:error] = "There was an error saving the question. Please try again."
  		render :new
  	end
  end

  def edit
  	@question = Question.find(params[:id])
  end

  def update
  	@question = Question.find(params[:id])
  	if @question.update_attributes(params.require(:question).permit(:title, :body, :resolved))
  		flash[:notice] = "Question was updated."
  		redirect_to @question
  	else
  		flash[:error] = "There was an error saving the question. Please try again."
  		render :edit
  	end
  end

  def destroy
  	@question = Question.find(params[:id])

  	if @question.destroy
  		flash[:notice] = "\"#{@question.title}\" was deleted successfully."
  		redirect_to questions_path
  	else
  		flash[:error] = "There was an error deleting the question."
  		render :show
  	end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for questions</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @question do |q| %>
       <div class="form-group">
         <%= q.label :title %>
         <%= q.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
       </div>
       <div class="form-group">
         <%= q.label :Body %>
         <%= q.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
       </div>
       <div class="form-group">
         <%= q.label :resolved %>
         <%= q.check_box :resolved %>
       </div>
       <div class="form-group">
         <%= q.submit "Submit", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/questions/index.html.erb
<h1>All Questions</h1>
	<% @questions.each do |question| %>
		<div class="media">
			<div class="media-body">
				<h4 class="media-heading">
					<%= link_to question.title, question %>
				</h4>
			</div>
		</div>
	<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for questions</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @question do |q| %>
       <div class="form-group">
         <%= q.label :title %>
         <%= q.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
       </div>
       <div class="form-group">
         <%= q.label :Body %>
         <%= q.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
       </div>
       <div class="form-group">
         <%= q.label :resolved %>
         <%= q.check_box :resolved %>
       </div>
       <div class="form-group">
         <%= q.submit "Submit", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p><%= @question.body %></p>
<p><%= @question.resolved %></p>

<div class="col-md-4">
	<%= link_to "Edit", edit_question_path(@question), class: "btn btn-success" %>
	<%= link_to "Delete Question", @question, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete this question?" } %>

</div>