config/routes.rb
Rails.application.routes.draw do

  resources :questions

  resources :advertisements

  resources :topics do
  	resources :posts, except: [:index]
    resources :sponsored_posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  post 'users/confirm' => 'users#confirm'

  get 'about' => 'welcome#about'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
	
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
  	belongs_to :user

  	validates :body, length: { minimum: 5 }, presence: true
  	validates :user, presence: true

  	after_create :send_favorite_emails
 
   	private
 
   	def send_favorite_emails
    	post.favorites.each do |favorite|
       		FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
    	end
  	end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
	belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  after_create :create_vote
  after_create :create_favorite

  default_scope { order('rank DESC') }
  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }


  scope :ordered_by_title, -> { order('title DESC') }
  scope :ordered_by_reverse_created_at, -> { order('created_at ASC') }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end

  def create_vote
    user.votes.create(value: 1, post: self)
  end

  def create_favorite
    Favorite.create(post: self, user: self.user)
    FavoriteMailer.new_post(self).deliver_now
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
end

app/models/sponsored_post.rb
class SponsoredPost < ApplicationRecord
	belongs_to :topic
	
end

app/models/topic.rb
class Topic < ApplicationRecord
	has_many :posts, dependent: :destroy
	has_many :sponsored_posts

	validates :name, length: { minimum: 5 }, presence: true
  	validates :description, length: { minimum: 15 }, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
	# callback
	before_save { self.email = email.downcase if email.present? }
	before_save :format_name
  before_save { self.role ||= :member }

	# validates presence and min/max length for name and email
	validates :name, length: { minimum: 1, maximum: 100 }, presence: true
	validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
  	
	# ensures when user pw is updated that they have a valid pw at least 6 characters long
	# allow_blank skips validation if no updated pw is given
  	validates :password, length: { minimum: 6 }, allow_blank: true

  	#validated email
   	validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 254 }

    # requires BCrypt to use. Used for hashing passwords
   	has_secure_password

    enum role: [:member, :admin, :moderator]


  def format_name
      if name
        name_array = []
        name.split.each do |name_part|
          name_array << name_part.capitalize
        end
          
        name = name_array.join(" ")
      end
    end

  def favorite_for(post)
    favorites.where(post_id: post.id).first
  end

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :user
  	belongs_to :post
  	after_save :update_post

  	validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true

  	private

  	def update_post
  		post.update_rank
  	end
end

app/controllers/sponsored_posts_controller.rb
class SponsoredPostsController < ApplicationController
  def new
  	@topic = Topic.find(params[:topic_id])
  	@sponsored_post = SponsoredPost.new
  end

  def show
  	@sponsored_post = SponsoredPost.find(params[:id])
  end

  def edit
  	@post = SponsoredPost.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def form_group_tag(errors, &block)
		css_class = 'form-group'
		css_class << ' has-errr' if errors.any?

		content_tag :div, capture(&block), class: css_class
	end

	def avatar_url(user)
     gravatar_id = Digest::MD5::hexdigest(user.email).downcase
     "http://gravatar.com/avatar/#{gravatar_id}.png?s=48"
   end
end

app/helpers/comments_helper.rb
module CommentsHelper
	def user_is_authorized_for_comment?(comment)
		current_user && (current_user == comment.user || current_user.admin?)
	end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def user_is_authorized_for_post?(post)
		current_user && (current_user == post.user || current_user.admin? || current_user.moderator?)
	end

	def user_is_authorized_for_delete?
		current_user && (current_user == post.user || current_user.admin?)
	end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def create_session(user)
		session[:user_id] = user.id
	end

	def destroy_session(user)
		session[:user_id] = nil
	end

	def current_user
		User.find_by(id: session[:user_id])
	end
end

app/helpers/sponsored_posts_helper.rb
module SponsoredPostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
	def user_is_authorized_for_topics?
		current_user && (current_user.admin? || current_user.moderator?)
	end

	def user_is_authorized_for_delete?
		current_user.admin?
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def user_posts_if_any(posts)
		if posts.any?
			render @user.posts
		else
			"#{current_user.name} has not submitted any posts yet."
		end
	end

	def user_comments_if_any(comments)
		if comments.any?
			render @user.comments
		else
			"#{current_user.name} has not submitted any comments yet."
		end
	end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/sponsored_posts/edit.html.erb
<h1>Edit Sponsored Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for sponsored posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for [@sponsored_post.topic, @sponsored_post] do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_field :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, class: 'form-control', placeholder: "Enter price" %>
    </div>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
    <% end %>
  </div>
</div>

app/views/sponsored_posts/new.html.erb
<h1>New Sponsored Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for sponosred posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for [@topic, @sponsored_post] do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, class: 'form-control', placeholder: "Enter price" %>
    </div>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
    <% end %>
  </div>
</div>

app/views/sponsored_posts/show.html.erb
<h1><%= @sponsored_post.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @sponsored_post.body %></p>
  </div>
  <div class = "col-md-4">
    <%= link_to "Edit", edit_topic_sponsored_post_path(@sponsored_post.topic, @sponsored_post), class: 'btn btn-success' %>
  </div>
</div>